default_platform(:ios)

platform :ios do
  desc "Build iOS app for Simulator"
  lane :build_simulator do
    gym(
      workspace: "./ios/expolocalbuildscicd.xcworkspace", 
      scheme: "expolocalbuildscicd",
      configuration: "Release",
      skip_package_ipa: true,
      build_path: "./output/filePath",
      output_directory: "./output/filePath",
      destination: "generic/platform=iOS Simulator"
    )
    FileUtils.cp_r("../output/filePath/Build/Products/Release-iphonesimulator/expolocalbuildscicd.app", "../output")
  end
end

platform :android do
  desc "Build Android debug APK"
  lane :build_debug do
    gradle(
      task: "assembleDebug",
      project_dir: "android",
      print_command: false
    )
  end
end
