name: Expo local builds CI IOS

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-ios:
    name: iOS Build (.app for simulator)
    runs-on: macos-14 # Ensures Xcode 15.3

    steps:
      - uses: actions/checkout@v4

      - name: Cache iOS build output
        id: cache-ios
        uses: actions/cache@v3
        with:
          path: ios/build/Build/Products/Release-iphonesimulator
          key: ios-build-${{ github.ref }}-${{ github.sha }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.1

      - name: Install dependencies
        run: yarn install

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Expo prebuild (iOS)
        run: npx expo prebuild --platform ios --non-interactive

      - name: Update CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod install
        working-directory: ./ios

      - name: Build iOS app for simulator
        run: |
          cd ios
          xcodebuild \
            -workspace expo-local-build-ci-cd.xcworkspace \
            -scheme expo-local-build-ci-cd \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_ENTITLEMENTS="" \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExpoApp.app
          path: ios/build/Build/Products/Release-iphonesimulator/*.app
