name: Expo Local Builds CI - iOS

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-ios:
    name: iOS Build (.app for Simulator)
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn install --frozen-lockfile

      - name: Install Expo CLI (Local)
        run: yarn add -D expo-cli

      - name: Configure Expo scheme
        run: |
          yarn expo config:set "scheme" "expolocalbuildscicd" --type public --non-interactive

      - name: Clean existing native folders
        run: rm -rf ios android

      - name: Run Expo prebuild for iOS (Objective-C)
        run: yarn expo prebuild --platform ios --non-interactive --no-install

      - name: Check for previous successful build on develop
        id: check_previous_build
        if: github.ref == 'refs/heads/develop'
        run: |
          PREVIOUS_BUILD=$(gh api "repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs" | jq -r '.check_runs[] | select(.name=="iOS Build (.app for Simulator)" and .conclusion=="success") | .id')
          if [[ -n "$PREVIOUS_BUILD" ]]; then
            echo "Previous build found — skipping"
            echo "::set-output name=skip_build::true"
          else
            echo "::set-output name=skip_build::false"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build iOS app (.app for Simulator)
        if: github.ref == 'refs/heads/main' || steps.check_previous_build.outputs.skip_build == 'false'
        env:
          BUNDLE_IDENTIFIER: com.uroge.expolocalbuildcicd
        run: |
          cd ios
          xcodebuild \
            -workspace expolocalbuildscicd.xcworkspace \
            -scheme expolocalbuildscicd \
            -configuration Release \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -derivedDataPath build \
            PRODUCT_BUNDLE_IDENTIFIER=$(echo "$BUNDLE_IDENTIFIER")

      - name: Upload built .app artifact
        if: github.ref == 'refs/heads/main' || steps.check_previous_build.outputs.skip_build == 'false'
        uses: actions/upload-artifact@v4
        with:
          name: expo-local-builds-ci-cd-simulator.app
          path: ios/build/Build/Products/Release-iphonesimulator/expolocalbuildscicd.app
