name: Export OTA Update

on:
  push:
    branches:
      - develop

jobs:
  ota-export:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Setup Expo
        run: npx expo install

      - name: Create OTA Build
        run: |
          mkdir dist
          npx expo export --dev --output-dir dist

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
